
insert into GESTAO_ACADEMICA_LINHA_PESQUISA (ATIVO, CODIGO_LINHA_PESQ, TITULO, SQ_PROGRAMA) VALUES ("S", "PP", "Políticas Públicas", 3);
insert into GESTAO_ACADEMICA_LINHA_PESQUISA (ATIVO, CODIGO_LINHA_PESQ, TITULO, SQ_PROGRAMA) VALUES ("S", "GAP", "Governança e Administração Pública", 3);


insert into GESTAO_ACADEMICA_EVENTO (ATIVO, SQ_TURMA, DATA_INICIO, DATA_FIM, SIGLA, DESCRICAO) VALUES ("S", 9, "2016-03-21", "2017-12-31", "PREPROJETO", "pre projeto");

insert into GESTAO_ACADEMICA_EVENTO (ATIVO, SQ_TURMA, DATA_INICIO, DATA_FIM, SIGLA, DESCRICAO) VALUES ("S", 9, "2016-03-21", "2017-12-31", "ORIENTACAO", "orientacao");

insert into GESTAO_ACADEMICA_EVENTO (ATIVO, SQ_TURMA, DATA_INICIO, DATA_FIM, SIGLA, DESCRICAO) VALUES ("S", 9, "2016-03-21", "2017-12-31", "PROJETO", "projeto");

insert into GESTAO_ACADEMICA_EVENTO (ATIVO, SQ_TURMA, DATA_INICIO, DATA_FIM, SIGLA, DESCRICAO) VALUES ("S", 9, "2016-03-21", "2017-12-31", "BANCA", "banca");



insert into GESTAO_ACADEMICA_USUARIO (ATIVO, NOME, LOGIN, EMAIL, SENHA, SQ_PERFIL) VALUES ("S", "Roberta Guimarães", "roberta", "roberta.guimaraes@fgv.br", "123",  3);

insert into GESTAO_ACADEMICA_USUARIO (ATIVO, NOME, LOGIN, EMAIL, SENHA, SQ_PERFIL) VALUES ("S", "Marcelo Almeida", "marcelo", "marcelo.almeida@fgv.br", "123",  6);

insert into GESTAO_ACADEMICA_USUARIO_PROGRAMA ( SQ_USUARIO, SQ_PROGRAMA) VALUES ( 442, 2);

insert into GESTAO_ACADEMICA_USUARIO_PROGRAMA ( SQ_USUARIO, SQ_PROGRAMA) VALUES ( 443, 2);